### ISSUE TITLE
プロダクト概要と見た目の話

### ISSUE THREAD

**Issue by keitakawamoto** [stskc/Recotte#2]
Recotteの見た目を手伝わせてもらう。
それにあたっていろいろと把握する。

**Comment by keitakawamoto** [comment]
## アプリケーション概要

- 「DAMにない曲がランダムで流れるアプリ」
- 「気に入ればDAMにリクエスト！」
- 「君のpushによってカラオケに追加されるかも！？」

## 機能

```
ユーザーはそのページにアクセス
@stskc ライブラリランダム再生
ユーザーはシェアできる
次の曲を再生
次の曲をスキップ
前の曲を再生
DAMへのリクエスト
```

## ランダム再生について

- youtube上にあるものすべてではない。DBに登録されているyoutubeの動画IDをランダムに変数に入れて、それを元にiframeでyoutubeから動画を持ってくる。
- `DBに登録されているyoutubeの動画ID` とは @stskc チョイスのライブラリ。
- いずれはユーザーごとにしたい

## 発端

```
satoshi [4:57 PM] 
元々はカラオケに自分の好きなアーティストの曲がないので
このサイトからjoysoundとかdam にリクエスト遅れるようにしたいなと思って始めたんですが、難しそうなので現状こんなかんじです
不特定多数の人から大量にリクエストがあれば実現できるんじゃ！とか思って

kawamoto [4:58 PM] 
なるほど〜

> joysoundとかdam にリクエスト遅れるようにしたい

のであれば、なぜランダムに？

satoshi [5:01 PM] 
そこは深く考えてませんでしたが、アクセスして流れる曲が分かったら気に入られなかったときに2回目のアクセスは望めないので、ランダムの方がよいかなと

kawamoto [5:02 PM] 
さとしライブラリ（DAMにない）が流れるアプリケーションを使って楽しむユーザーは、「おっ」と思ったその曲をDAMにリクエストできる
と。
曲名を知られればアクセスされないので全部均等に流れる工夫がランダム
そして
「ユーザーがDAMに追加したい曲をリクエストできるアプリ」ではなく
「さとしがDAMに追加したい曲がランダムで流れるアプリ」であり、使った人が、気に入ればDAMにリクエストする (edited)
ということか

satoshi [5:08 PM] 
ですね、何か改めて文字に起こすとはずかしいですね
```


## 名前

- 推薦する意味のRecommendから
- `レコって！！！！`
- **Recotte**

**Comment by keitakawamoto** [comment]
## プロトタイプ

```
ユーザーはそのページにアクセス
@stskc ライブラリランダム再生
ユーザーはシェアできる
次の曲を再生
次の曲をスキップ
前の曲を再生
```

`DAMへのリクエスト` が含まれない、曲がランダム再生されるラジオ的なアプリケーション。

**Comment by keitakawamoto** [comment]
## 現状

![image](https://cloud.githubusercontent.com/assets/1661325/15317158/3bc00d38-1c5b-11e6-9b31-389a3daa92eb.png)

ブートストラップで構成。
ブートストラップは廃止。
こちらでhtml/cssで構成する。
まずはレイアウトを用意。

**Comment by stskc** [comment]
@keitakawamoto 
ブートストラップのgemの削除とCSSの記述削除しました！

**Comment by stskc** [comment]
![20160517](https://cloud.githubusercontent.com/assets/13348605/15319406/a1936ede-1c65-11e6-8e2d-b5d2b6543a9d.png)

**Comment by keitakawamoto** [comment]
@stskc まっさらにしてくれてサンキュー！かなりやりやすい。
こちらはまずはレイアウトを考案するから、その後実装に入るので気長に待ってて

**Comment by keitakawamoto** [comment]
@stskc 
合格おめでとう！！！
Recotte開発に余裕が出たとのことなので、ひとりで開発する力をつけるために、手伝いはキャンセル。
楽しみにしとく 👍

**Comment by stskc** [comment]
@keitakawamoto ありがとうございます！
